<a href="https://colab.research.google.com/github/OluwatodimuAdegoke/ComputerVisionCourse/blob/main/ComputerVision_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np

In [ ]:
A = np.random.normal(2,2,size=(4,2,3))
# Converts to tensor
A = tf.convert_to_tensor(A)
print(A)
# Expand and Squeeze a tensor
A = (tf.expand_dims(A,axis=0))
print(A)
print(tf.squeeze(A,axis = 0))
# Reshapes the tensor
print(tf.reshape(A,(2,2,6)))

In [5]:
# Concatenate tensors along an axis
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])
tf.concat([t1,t2],axis = 1)
# Use tf.stack to add a new axis

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [12]:
#pad
p1 = tf.constant([[1,2,3],[4,5,6]])
p2 = tf.constant([[2,4],[3,5]])
print(tf.pad(p1,p2,"CONSTANT",constant_values=0))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0 0 0]
 [0 0 0 4 5 6 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]], shape=(8, 11), dtype=int32)


In [36]:
# Gather, an alternative to indexing
# Use axis, to output the column
tf.gather(p1,[0,1],axis = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [49]:
# gather_nd . Use batch_dims to choose an axis
indices = [[0,1],[1,0]]
params = [['a','b'],['c','d'],['e','f']]
tf.gather_nd(params,indices,batch_dims = 0)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b', b'c'], dtype=object)>

In [55]:
# RaggedTensor - to create an uneven tensor (not rectangular)
tensor_two_d = tf.ragged.constant([[1,2,0],[3,5],[1,5,6],[2,3,8]])
print((tensor_two_d))
# Use ragged.boolean_mask to remove some values with a mask array

<tf.RaggedTensor [[1, 2, 0], [3, 5], [1, 5, 6], [2, 3, 8]]>


In [57]:
# Spare Tensors - contains a lot of zeros
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values=[11,44] , dense_shape = [5,6]
)
print(tf.sparse.to_dense(tensor_sparse))


tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 44  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)
