<a href="https://colab.research.google.com/github/OluwatodimuAdegoke/ComputerVisionCourse/blob/main/Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,3],[1,2,3]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],[2,3,4]],[[1,2,0],[2,3,4]],[[1,2,0],[2,3,4]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 0]
  [2 3 4]]

 [[1 2 0]
  [2 3 4]]

 [[1 2 0]
  [2 3 4]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(3, 2, 3)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
#Identity matrix
eye_tensor = tf.eye(5,2)
print(3*eye_tensor)

tf.Tensor(
[[3. 0.]
 [0. 3.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(5, 2), dtype=float32)


In [ ]:
#Creates a tensor filled with a scalar value
fill_tensor = tf.fill([3,4],5)
print(fill_tensor)
#Creates a tensor with only ones, there is also tf.zero and tf.zeros_like
one_tensor = tf.ones([5,5])
print(one_tensor)
#Creates a tensor of ones with the same shape as the input
tf.ones_like(fill_tensor)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:

#Create random values, there is also tf.random.uniform(shape,minval, maxval)
random_tensor = tf.random.normal([3,3],mean=0.0,stddev=1.0,dtype=tf.dtypes.float32)
print(random_tensor)

tf.Tensor(
[[ 0.4661633   0.36314335 -0.7084536 ]
 [-0.19733104 -0.02985091 -0.74808335]
 [ 0.8338513   0.04642004 -0.7173452 ]], shape=(3, 3), dtype=float32)


**Tensor Indexing**

In [ ]:
# Uses [minindex:maxindex+1:step]
# 1D
tensor_indexed = tf.constant([2,4,4,5,2])
print(tensor_indexed)
print(tensor_indexed[1:4+1])

tf.Tensor([2 4 4 5 2], shape=(5,), dtype=int32)
tf.Tensor([4 4 5 2], shape=(4,), dtype=int32)


In [ ]:
# 2D
tensor_two_d = tf.constant([
    [1,2,0],
    [2,4,5],
    [6,7,8],
    [4,5,6]
])
print(tensor_two_d[0:2,:])

tf.Tensor(
[[1 2 0]
 [2 4 5]], shape=(2, 3), dtype=int32)


**Linear Algebra**

In [ ]:
# Matric multiplication
x_1 = tf.constant([[10,0],[1,2]], dtype = tf.float32)
x_2 = tf.constant([[1,2,2],[5,3,2]], dtype = tf.float32)

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[10. 20. 20.]
 [11.  8.  6.]], shape=(2, 3), dtype=float32)


In [ ]:
# Get the inverse of a matrix. matrix * inverse gets the identity matrix
print(tf.linalg.inv(x_1)@x_1)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
# SVD
print(tf.linalg.svd(x_1))

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.051928 ,  1.9896687], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.99462306, -0.1035621 ],
       [ 0.1035621 ,  0.99462306]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.99978775, -0.02060542],
       [ 0.02060542,  0.99978775]], dtype=float32)>)


In [ ]:
# Einsum Operator np.einsum(("ij,jk -> ik", A, B))
# The einsum allows you to use your own formula
# E.g np.einsum("ij,ij -> ij",A,B)
x_3 = tf.constant([[10,0],[1,2]], dtype = tf.float32)
x_4 = tf.constant([[10,0],[1,2]], dtype = tf.float32)
print(np.einsum('ij -> ji',x_3))
print(np.einsum('ij,ij -> ij',x_3,x_4))
print(np.einsum('ij,jk -> ik',x_3,x_4))

[[10.  1.]
 [ 0.  2.]]
[[100.   0.]
 [  1.   4.]]
[[100.   0.]
 [ 12.   4.]]


In [ ]:
# 3D Arrays
A = np.ones((2,3,4))
B = np.random.normal(3,2,size=(2,4,5))
print("Multiplication :")
print( np.einsum('aij,ajk -> aik',A,B) )

# Sum Array
print("Sum :")
print(np.einsum('ijk-> i',A))

Multiplication :
[[[ 4.94399712  5.80575812 16.13045203 18.37462865 13.2445404 ]
  [ 4.94399712  5.80575812 16.13045203 18.37462865 13.2445404 ]
  [ 4.94399712  5.80575812 16.13045203 18.37462865 13.2445404 ]]

 [[13.55982593  8.77374703  4.8378012  12.30892497 10.05203428]
  [13.55982593  8.77374703  4.8378012  12.30892497 10.05203428]
  [13.55982593  8.77374703  4.8378012  12.30892497 10.05203428]]]
Sum :
[12. 12.]
