<a href="https://colab.research.google.com/github/OluwatodimuAdegoke/ComputerVisionCourse/blob/main/ComputerVision_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
A = np.random.normal(2,2,size=(4,2,3))
# Converts to tensor
A = tf.convert_to_tensor(A)
print(A)
# Expand and Squeeze a tensor
A = (tf.expand_dims(A,axis=0))
print(A)
print(tf.squeeze(A,axis = 0))
# Reshapes the tensor
print(tf.reshape(A,(2,2,6)))

tf.Tensor(
[[[1.87552145 6.65821618 4.31647342]
  [8.59038377 4.69625433 1.02071674]]

 [[2.24218268 0.18069138 3.67079746]
  [3.27125364 0.2821315  2.71701496]]

 [[4.78692744 3.89517446 3.06059111]
  [0.05921844 2.91374654 2.11160097]]

 [[2.89308139 2.1545724  4.26254301]
  [2.68609388 1.5307742  1.79841674]]], shape=(4, 2, 3), dtype=float64)
tf.Tensor(
[[[[1.87552145 6.65821618 4.31647342]
   [8.59038377 4.69625433 1.02071674]]

  [[2.24218268 0.18069138 3.67079746]
   [3.27125364 0.2821315  2.71701496]]

  [[4.78692744 3.89517446 3.06059111]
   [0.05921844 2.91374654 2.11160097]]

  [[2.89308139 2.1545724  4.26254301]
   [2.68609388 1.5307742  1.79841674]]]], shape=(1, 4, 2, 3), dtype=float64)
tf.Tensor(
[[[1.87552145 6.65821618 4.31647342]
  [8.59038377 4.69625433 1.02071674]]

 [[2.24218268 0.18069138 3.67079746]
  [3.27125364 0.2821315  2.71701496]]

 [[4.78692744 3.89517446 3.06059111]
  [0.05921844 2.91374654 2.11160097]]

 [[2.89308139 2.1545724  4.26254301]
  [2.68609388 1.

In [ ]:
# Concatenate tensors along an axis
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])
tf.concat([t1,t2],axis = 1)
# Use tf.stack to add a new axis

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [ ]:
#pad
p1 = tf.constant([[1,2,3],[4,5,6]])
p2 = tf.constant([[2,4],[3,5]])
print(tf.pad(p1,p2,"CONSTANT",constant_values=0))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0 0 0]
 [0 0 0 4 5 6 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]], shape=(8, 11), dtype=int32)


In [ ]:
# Gather, an alternative to indexing
# Use axis, to output the column
tf.gather(p1,[0,1],axis = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
# gather_nd . Use batch_dims to choose an axis
indices = [[0,1],[1,0]]
params = [['a','b'],['c','d'],['e','f']]
tf.gather_nd(params,indices,batch_dims = 0)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b', b'c'], dtype=object)>

In [ ]:
# RaggedTensor - to create an uneven tensor (not rectangular)
tensor_two_d = tf.ragged.constant([[1,2,0],[3,5],[1,5,6],[2,3,8]])
print((tensor_two_d))
# Use ragged.boolean_mask to remove some values with a mask array

<tf.RaggedTensor [[1, 2, 0], [3, 5], [1, 5, 6], [2, 3, 8]]>


In [ ]:
# Spare Tensors - contains a lot of zeros
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values=[11,44] , dense_shape = [5,6]
)
print(tf.sparse.to_dense(tensor_sparse))


tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 44  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


In [7]:
# Variables
v = tf.Variable(1.)
x_var = tf.Variable([2,2])
v.assign(2.)
print(v)
v.assign_add(2)
v.assign_sub(3)
print(x_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>
